### ISSUE TITLE
Adopting linter

### ISSUE THREAD

**Issue by sigmafelix** [Spatiotemporal-Exposures-and-Toxicology/amadeus#2]
My PR's workflows are adopted from `chopin`'s. Do we want to use linter for `amadeus`?

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
**For sure!**

![image](https://github.com/Spatiotemporal-Exposures-and-Toxicology/amadeus/assets/127860447/66386e5b-7547-4a40-a510-f7f9000098e2)

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix @mitchellmanware

I think an initial grace period from branch protection rules (ie. mandatory tests like pull requests, etc.) is okay. Once you have the basic stuff transferred over, let me know, and then I'll add the rules

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology I will add a linter as well. We will need to work on system-specific problems (i.e., related to command-line tools) as the tests passed only in linux runners.

**Comment by mitchellmanware** [comment]
@sigmafelix
I had not considered that before, but yes, I will have to create additional functions for system detection + system-specific command writing.

For linting, implementing on all pushes could help identify lint related issues earlier in branches and avoid PRs being hung up on whitespace or indentation issues.

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology @mitchellmanware  The errors seem to be related to settings in Action runner images. I am looking into it. I will enable linter in the next push. Thanks!
