### ISSUE TITLE
New tests

### ISSUE THREAD

**Issue by mitchellmanware** [Spatiotemporal-Exposures-and-Toxicology/amadeus#25]
Create additional tests for robust and integration testing.

- [x] download.R
  - [x] Live download run to cover `download_run()` and zip file commands
- [x] download_support.R
  - [x] `download_run(download = TRUE)`
  - [x] `download_sink()`
  - [x] `download_unzip(unzip = TRUE)`
  - [x] `download_remove_zips(remove = TRUE)`
- [x] download_test_support.R
  - [x] Missing position in `extract_urls()`
  - [x] Missing sample size in `check_urls()`
- [x] calculate_covariates.R
- [x] manipulate_spacetime_data.R

**Comment by eva0marques** [comment]
The crs defined by default is NA which is not a character. It is a bug I should have fixed, as many other bugs. But this function is to be deleted as soon as we are sure that we can replace everything with sftime. I am not sure you should spend time on it.

**Comment by mitchellmanware** [comment]
For `download_ecoregion_data` and `download_gmted_data` I removed the `if(download)` as a trigger for the `download_unzip()` and `download_remove_zips()` functions. The functions now rely on the `unzip = ` and `remove_commands = ` parameters to run/skip the functions.

Before:
```
  if (download) {
    #### 17. end if unzip == FALSE
    download_unzip(
      file_name = download_name,
      directory_to_unzip = directory_to_save,
      unzip = unzip
    )
    #### 19. remove zip files
    download_remove_zips(
      remove = remove_zip,
      download_name = download_name
    )
  }
}
```

After 
```
  #### 18. end if unzip == FALSE
  download_unzip(
    file_name = download_name,
    directory_to_unzip = directory_to_save,
    unzip = unzip
  )
  #### 19. remove zip files
  download_remove_zips(
    remove = remove_zip,
    download_name = download_name
  )
```

Changes result in negligable performance differences and increased code coverage.
GMTED data
```
> microbenchmark(
+   ## original function with if(download)
+   download_gmted_data_original(
+     statistic = "Breakline Emphasis",
+     resolution = "7.5 arc-seconds",
+     directory_to_download = d,
+     directory_to_save = d,
+     data_download_acknowledgement = TRUE,
+     download = FALSE,
+     remove_command = TRUE
+   ),
+   ## remove if(download); rely on `unzip` and `remove_zip` triggers
+   download_gmted_data(
+     statistic = "Breakline Emphasis",
+     resolution = "7.5 arc-seconds",
+     directory_to_download = d,
+     directory_to_save = d,
+     data_download_acknowledgement = TRUE,
+     download = FALSE,
+     remove_command = TRUE,
+     unzip = FALSE
+   ),
+   times = 5,
+   unit = "seconds"
+ )
      min       lq     mean   median       uq      max neval
 2.135385 2.202835 2.211150 2.203547 2.211668 2.302315     5
 2.173169 2.179900 2.279153 2.258105 2.356912 2.427681     5
```

Ecoregion data
```
> microbenchmark(
+   download_ecoregion_data_original(
+     directory_to_download = d,
+     directory_to_save = d,
+     data_download_acknowledgement = TRUE,
+     download = FALSE,
+     remove_command = TRUE
+   ),
+   download_ecoregion_data(
+     directory_to_download = d,
+     directory_to_save = d,
+     data_download_acknowledgement = TRUE,
+     download = FALSE,
+     remove_command = TRUE,
+     unzip = FALSE
+   ),
+   times = 5,
+   unit = "seconds"
+ )
      min       lq     mean   median       uq      max neval
 2.345228 2.347249 2.432835 2.414153 2.448946 2.608599     5
 2.201068 2.254072 2.311288 2.301413 2.368630 2.431258     5
```

**Comment by mitchellmanware** [comment]
New tests for `calculate_covariates` added in https://github.com/Spatiotemporal-Exposures-and-Toxicology/amadeus/pull/26. These new unit tests will be pulled into version 0.1.2
