### ISSUE TITLE
sf and sftime changes instead of sdst functions

### ISSUE THREAD

**Issue by Spatiotemporal-Exposures-and-Toxicology** [Spatiotemporal-Exposures-and-Toxicology/amadeus#6]

**Comment by eva0marques** [comment]
# To do list

In `R/manipulate_spacetime_data.R` (and `tests/testthat/test-manipulate_spacetime_data.R`):
- [ ] adapt `is_stdt()` to a new fonction `is_mysftime()` to see if lat, lon, time columns are included in the sftime. (Also a version for `is_mysf()`?)
- [ ] test for `is_mysftime()` and `is_mysf()`
- [ ] adapt `convert_stobj_to_stdt()` to a new function to `as_mysftime()`: conversion for data.table (suppl. arg: crs, tzone, lat, lon, time colnames), SpatRaster, SpatVector, sftime (suppl. arg: lat, lon, time colnames) 
- [ ] test for `as_mysftime()` and subsequent functions
- [ ] turn `convert_stdt()` into 2 functions `mysftime_to_SpatVector()` and `mysftime_to_SpatRasterDs()`
- [ ] test for `mysftime_to_SpatVector()` and `mysftime_to_SpatRasterDs()`

Note: calling functions `is_smthg` and `as_smthg` implies we are coding OO in a manner. 

In `R/calculate_covariates.R`, 'tests/testthat/test-calculate_covariates.R`, :
- [ ] replace `is_stdt()` by `is_mysftime()`
- [ ] replace  `convert_stdt_blabla()` by `mysftime_to_blabla()`
- [ ] replace `convert_stobj_to_stdt()` by `as_mysftime()`
- [ ] remove every call to `blabla$stdt`
- [ ] replace every `blabla$crs` by `attributes(sftime_x)$crs` (it is a crs object and not a character!). Storing crs in a variable might not be relevant anymore. 
- [ ] See if this code is still relevant:
`if (!all(c("lon", "lat", "time") %in% colnames(sites))) {
      stop("sites should be stdt or 
      have 'lon', 'lat', and 'time' fields.\n")
    }`

In `calculate_covariates_support.R`:
- [ ] check if `stdtile` is related to stdt class. 

That's all the call I found in amadeus. Once it's done, check in beethoven vignettes.

**Comment by eva0marques** [comment]
In case anything goes wrong with this issue, I duplicated main branch before changes in a new branch "save_branch_stdt.

**Comment by eva0marques** [comment]
Notes:
- terra::vect() function works to convert `sf` class to `SpatVector` (but not for `sftime` class: see new function).

**Comment by eva0marques** [comment]
@mitchellmanware @sigmafelix 
I have added to my todo to remove all calls to stdt functions in calc_covariates.R but I cannot find any of them anymore (which is very cool!!) But I just wanna check with you I am not hallucinating (it can happen sometimes 🫨🫣): did I miss something, you've already removed them?

**Comment by sigmafelix** [comment]
@eva0marques At least in `amadeus` functions I've been working on, I replaced lines with `stdt` calls with generic functions (e.g., `sf` or `terra` functions). `stdt` compatibility is necessary at this moment as cross-validation indexing functions in `beethoven` rely on `stdt`.

**Comment by eva0marques** [comment]
Ok, thanks! So to let you know, I implemented all the conversion functions you can see in my comment above.
