### ISSUE TITLE
move download and calc covariate functionality to amadeus

### ISSUE THREAD

**Issue by Spatiotemporal-Exposures-and-Toxicology** [Spatiotemporal-Exposures-and-Toxicology/amadeus#7]

**Comment by mitchellmanware** [comment]
NARR, GMTED, HMS, and GEOS `process` and `calc` functions have been copied from beethoven into branch mm-copy-functions. `calc` functions have been added to existing `calculate_covariates.R` file and wrapper functionality.

**Comment by mitchellmanware** [comment]
I agree they should be removed. We should also consider changing the default directories for the data download functions.

**Comment by sigmafelix** [comment]
Per #19, I think we can close this and related issues. Thanks for your hard work!
