### ISSUE TITLE
`import_hms` and `covar_hms`

### ISSUE THREAD

**Issue by mitchellmanware** [Spatiotemporal-Exposures-and-Toxicology/amadeus#9]

**Comment by sigmafelix** [comment]
I think missing dates could be handled after covariates will be calculated. If we want to distinguish the missing dates from no category value, the problem gets a bit more complicated. In the example above, I think it will be fine to binding `SpatVector`s with and without geometries as null geometries can be removed with [`na.omit`](https://search.r-project.org/CRAN/refmans/terra/html/na.omit.html).

As a side note, we will need to add notes in the documentation to highlight the users' responsibility to check if datasets were truly missing on certain dates or these data were just not downloaded for any possible reasons (download errors, argument input mistakes, etc.).
